export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  JOBS: '/jobs',
  JOB_DETAIL: (id: string) => `/jobs/${id}` as const,
  NEW_JOB: '/dashboard/jobs/new',
  EDIT_JOB: (id: string) => `/dashboard/jobs/${id}/edit` as const,
  ENGAGEMENTS: '/dashboard/engagements',
  SAVED_JOBS: '/dashboard/saved-jobs',
  DASHBOARD_APPLICATIONS: '/dashboard/applications',
  DASHBOARD_APPLICATION_DETAIL: (id: string) => `/dashboard/applications/${id}` as const,
  TALENTS: '/talents',
  TALENT_DETAIL: (id: string) => `/talents/${id}` as const,
  PROFILE: '/dashboard/profile',
  CLIENT_PROFILE: '/dashboard/client-profile',
  CLIENT_PROFILE_DETAIL: (id: string) => `/clients/${id}` as const,
  SETTINGS: '/dashboard/settings',
} as const
